### ISSUE TITLE
How to launch polybar?

### ISSUE THREAD

**Issue by MykolaVaskevych** [SwiftyChicken/dotfiles#3]
In all tutorials saying that launch.sh file needed, but I can't find him.

**Comment by AbbasSrour** [comment]
In case someone else has the same problem check the .xinitrc and the bin folder

**Comment by SwiftyChicken** [comment]
In case someone is still wondering how my polybar works all the config files are located ~/.config/polybar/
- ../config : the main file which contains the colors, bars and general settings.
- ../modules/<name> : files in this folder contains all the modules for the <name> bar
- ../scripts/* : this are all the scripts that are used by the modules (hopefully I will organise this at a later date)

To start all the bars at once I made a script named dock.sh which is loctated in the ~/.local/bin/ folder. Personally added this folder to my PATH env variable (which is not necessary) so I can easily call dock.sh at startup.
(Meaning adding it in your xinitrc)
