### ISSUE TITLE
Polybar dbus Issue

### ISSUE THREAD

**Issue by godspeed1709** [SwiftyChicken/dotfiles#5]
There's a "dbus[ ]: arguments" error in the status bar

**Comment by godspeed1709** [comment]
Error of bluetoothd and dbus... solved by commenting this part from the module and bar

**Comment by SwiftyChicken** [comment]
I will update the bluetooth status so this error doesn't appear again when bluez is not installed

**Comment by SwiftyChicken** [comment]
Nevermind I should've already done that maybe you hadn't the latest script version of ~/.config/polybar/scripts/bluetooth-status.sh which contains this first line:
``` bash
! command -v bluetoothctl &> /dev/null && echo "%{F#6c809e}󰂯%{F-}" && exit 0
```
